version: '3.3'

services:


  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=root
    - POSTGRES_DB=test
    ports:
    - 5432:5432


#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test
#    ports:
#      - 3306:3306