spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
